name = "inovare-medicos"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2026-05-21"
compatibility_flags = ["nodejs_compat"]

[vars]
# CLINIC_PLACE_ID = "ChIJN3Bz2lwa6JQRzi0rQrcYanw"
